#!/bin/bash

debug=""
if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
    debug="--debug"
fi
set -eu
set -o pipefail

install "${debug}" --preserve-context -m 0755 -o root -g root $(dirname $0)/../bin/* /usr/local/bin || :
